groups:
  - name: novaledger-rules
    interval: 10s
    rules:
      - alert: ApiHighLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le)) > 0.3
        for: 30s
        labels:
          severity: warning
