apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: novaledger
resources:
  - namespace.yaml
  - deployment-api.yaml
  - deployment-worker.yaml
  - service-api.yaml
  - ingress.yaml
  - hpa-api.yaml
